### PR TITLE
add ttach package

### PR DESCRIPTION
**Pull request by juansensio**
add ttach package

https://github.com/qubvel/ttach

### CODE REVIEW

**Comment by isms** [comment]
@juansensio The build fails with this:
```
Encountered problems while solving:
  - nothing provides requested ttach
```

**Comment by juansensio** [comment]
hmm... should I do something else apart from adding the name of the library in the environment files ?

**Comment by isms** [comment]
Seems like it doesn't have a conda package available -- maybe try putting it under the `pip` section?

**Comment by juansensio** [comment]
Of course, my bad. Now it is in the right section. Thanks.

**Comment by isms** [comment]
Thanks @juansensio - this fix made it in manually when we pinned the versions this morning so closing the PR.

**Pull request closed without merging**
