### PR TITLE
add mmsegmentation & mmcv-full

### PR DESCRIPTION
**Pull request by aelbakry**
add support for mmsegmentation and mmcv

### CODE REVIEW

**Comment by isms** [comment]
@aelbakry Looks like the build failed due to a lack of prerequisites. Can you try building this with Docker and see if there is a fix?

**Comment by aelbakry** [comment]
I believe its because of mmcv-full support CUDA ops, replaced with mmcv lite version on cpu.

**Comment by isms** [comment]
@aelbakry Looks like the GPU build is failing because it can't find `g++`. You may want to try adding `build-essential` to `apt.txt`.

**Comment by isms** [comment]
Looks like we're good - thanks @aelbakry, merged!

**Pull request merged**
